//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_type : BaseModel
    {
        public int ID { get; set; }
        public int ByName { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
