//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer : BaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int ID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Name must not be empty.")]
        [MaxLength(45, ErrorMessage = "Maximum of 45 characters is allowed.")]
        public string FullName { get; set; }
        
        public System.DateTime DOB { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Identity Card must not be empty.")]
        [MaxLength(15, ErrorMessage = "Maximum of 12 characters is allowed.")]
        public string IdentityCard { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Phone must not be empty.")]
        [MaxLength(12, ErrorMessage = "Maximum of 12 characters is allowed.")]
        public string Phone { get; set; }
        public bool isForeigner { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public Nullable<int> DeletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
    }
}
