//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_details
    {
        public int BookDetailID { get; set; }
        public int ServiceDetailsID { get; set; }
        public int ServiceID { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual booking_details booking_details { get; set; }
        public virtual service service { get; set; }
    }
}
